#!/bin/bash

HOST=$1
VNXSRCDIR=/root/vnx/workspace/vnx-unstable/vnx/
#VNXSRCDIR=/almacen/vnx/workspace/vnx/
REMOTETMPDIR=vnx-update

#ssh $1 "cd /tmp; mkdir -p $REMOTETMPDIR && rm -rf $REMOTETMPDIR/\*"
# Create tmpdir and delete content if already created
ssh $1 "mkdir -vp /tmp/$REMOTETMPDIR; rm -vrf /tmp/$REMOTETMPDIR/*"
# Copy tar file
scp $VNXSRCDIR/distrib/vnx-latest.tgz $1:/tmp/$REMOTETMPDIR
# Uncompress vnx and install
ssh $1 "cd /tmp/$REMOTETMPDIR; tar xfvz vnx-latest.tgz; cd vnx-*; ./install_vnx"
