#!/bin/bash

if [ $1 = "config" ]; then
  CONFIG="true"
  VER=$2
else
  VER=$1
fi

service libvirt-bin stop
cd /root/src/libvirt-$VER
if [ $CONFIG ]; then
  ./configure --without-xen --prefix=/usr || (echo "ERROR in configure command"; exit)
  sed -i -e 's#-L /usr/lib#-L/usr/lib#' config.status
  make && make install
else
  make install
fi
rm /usr/lib/libvirt.so.0
ln -s /usr/lib/libvirt.so.$VER /usr/lib/libvirt.so.0
rm /usr/lib/libvirt-qemu.so.0
ln -s /usr/lib/libvirt-qemu.so.$VER /usr/lib/libvirt-qemu.so.0
service libvirt-bin start
