#!/bin/bash

# run as root 


# Remove install icon and examples folder that would otherwise be copied to the Desktop
rm -rf /usr/share/applications/ubiquity-gtkui.desktop
rm -rf /usr/share/example-content
rm -rf /etc/skel/examples.desktop

# vnx-user (de momento no funciona)
# sed -i -e "s/export USERNAME=\"ubuntu\"/export USERNAME=\"vnx-user\"/g" /etc/casper.conf
    
	
#############
#VNX
#############
    # Package Installation
    # Enable universe and multiverse
    cp /etc/apt/sources.list /etc/apt/sources.list.backup
    sed -i -e "s/# deb/deb/g" /etc/apt/sources.list

    # Update and install
    apt-get update
    #apt-get install -y build-essential qemu-kvm libvirt-bin vlan xterm bridge-utils  screen virt-manager virt-viewer libxml-checker-perl libxml-parser-perl libnetaddr-ip-perl libnet-pcap-perl libnet-ipv6addr-perl liberror-perl libexception-class-perl uml-utilities libxml-libxml-perl libxml2-dev libgnutls-dev libdevmapper-dev libterm-readline-perl-perl libnet-telnet-perl libnet-ip-perl libreadonly-perl libmath-round-perl libappconfig-perl libdbi-perl graphviz libnl-dev genisoimage gnome-terminal libfile-homedir-perl w3m
    apt-get -y dist-upgrade
    apt-get -y install build-essential qemu-kvm libvirt-bin vlan xterm \
        bridge-utils  screen virt-manager virt-viewer libxml-checker-perl \
        libxml-parser-perl libnetaddr-ip-perl libnet-pcap-perl \
        libnet-ipv6addr-perl liberror-perl libexception-class-perl \
        uml-utilities libxml-libxml-perl libxml2-dev libgnutls-dev \
        libdevmapper-dev libterm-readline-perl-perl libnet-telnet-perl \
        libnet-ip-perl libreadonly-perl libmath-round-perl libappconfig-perl \
        libdbi-perl graphviz libnl-dev genisoimage gnome-terminal \
        libfile-homedir-perl python-dev libsasl2-dev tree \
        wireshark nmap aptsh w3m

    # If you use 64 bits version of Ubuntu, install 32 bits compatibility libraries:
    # apt-get install ia32-libs

    #Install libvirt 0.9.3:
    stop libvirt-bin
    wget http://libvirt.org/sources/libvirt-0.9.3.tar.gz
    tar xfvz libvirt-0.9.3.tar.gz
    cd libvirt-0.9.3
    ./configure --without-xen --prefix=/usr && make && make install
    start libvirt-bin

    # For Ubuntu 10.04, just install the libsys-virt-perl package
    apt-get -y install libsys-virt-perl

    # Install VNX:
    mkdir -p /tmp/vnx-update
    cd /tmp/vnx-update
    wget -N http://idefix.dit.upm.es/download/vnx/vnx-latest.tgz
    tar xfvz vnx-latest.tgz
    cd vnx-*
    ./install_vnx
    mv /etc/vnx.conf.sample /etc/vnx.conf
    

#############


cd /tmp

# No users with a UID > 999
usermod -u 500 vnx
usermod -u 501 nobody
	
#chroot edit awk -F: '$3 > 999' /etc/passwd | awk -F: '{print "usermod -u 500" $1}' | bash


# Steps for vnx_install_fs.sh script
#
# set environment variable HOME to /root/.
HOME=/root
# install curl
apt-get -y install curl


#./vnx_install_fs.sh

exit 0	
	
	
