#! /bin/sh

. /etc/rc.subr

name="vnxdaemon"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"
restart_cmd="${name}_restart"

extra_commands="status restart"

vnxdaemon_start()
{
   echo 'starting vnxdaemon...'
   echo 'running' > /var/run/${name}.status
   perl /usr/sbin/vnxdaemon.pl &
   echo '...done'
}
vnxdaemon_stop()
{
   echo 'stopping vnxdaemon...'
   echo 'stopped' > /var/run/${name}.status
   kill -INT `cat /var/run/vnxdaemon.pid`
   rm /var/run/vnxdaemon.pid
   echo '...done'
}
vnxdaemon_status()
{
   echo 'vnxdaemon status: '
   cat /var/run/${name}.status
}
vnxdaemon_restart()
{
   echo 'restarting vnxdaemon...'
   
   if [ -f /var/run/vnxdaemon.pid ]
   then
      kill -INT `cat /var/run/vnxdaemon.pid`
      echo 'stopped' > /var/run/${name}.status
      rm /var/run/vnxdaemon.pid
   fi
   
   perl /usr/sbin/vnxdaemon.pl &
   echo 'running' > /var/run/${name}.status
   echo '...done'
}

load_rc_config $name
run_rc_command "$1"
