#!/bin/sh

VNX_VERSION="0.14b"
ROOTFS_VERSION="es-v023b"

# Move to the directory where this script is
cdir=$( dirname $0 )
cd $cdir

# Get perl modules directory (/usr/local/share/perl/5.10.0/ in Ubuntu)
PERL_LIBS=$(perl -e 'use Config; print $Config{installvendorlib}')
if [ ! $PERL_LIBS ]
then
   echo "ERROR: cannot find perl modules directory"
   exit 1
fi
VNX_LIBS="$PERL_LIBS/VNX/"

echo "** "
echo "** Installing VNX v${VNX_VERSION}... "
echo "** "

#
# Create directories if not already created
#
mkdir -vp ${VNX_LIBS}
mkdir -vp /usr/share/xml/vnx
mkdir -vp /usr/share/vnx/bin
mkdir -vp /usr/share/vnx/examples/
mkdir -vp /usr/share/vnx/filesystems
mkdir -vp /usr/share/vnx/kernels
mkdir -vp /usr/share/vnx/aced

#
# Copy vnx
#
cp -v bin/vnx /usr/bin
chmod +x /usr/bin/vnx

#
# Copy vnx perl modules
#
cp -v perl-modules/VNX/* ${VNX_LIBS}
chmod 644 ${VNX_LIBS}*

#
# Copy vnx dtd and xsd
#
cp -v data/*.dtd /usr/share/xml/vnx/
cp -v data/*.xsd /usr/share/xml/vnx/

#
# Copy examples
#
cp -v data/*.xml data/*.net /usr/share/vnx/examples/
cp -vr data/conf /usr/share/vnx/examples/
chmod 644 /usr/share/vnx/examples/*

#
# Copy other utils
#
cp -v bin/update_daemon.pl /usr/share/vnx/bin/vnx_update_aced
cp -v bin/vnx_modify_rootfs.sh /usr/share/vnx/bin/vnx_modify_rootfs
chmod 755 /usr/share/vnx/bin/*

#
# Copy vnx config file
#
if [ -e /etc/vnx.conf ]; then
	mv /etc/vnx.conf /etc/vnx.conf.bak
fi
cp -v data/vnx.conf /etc

#
# Copy ace daemons 
#
cp -v aced/* /usr/share/vnx/aced

echo "** "
echo "** ...done"
echo "** "