#!/bin/bash

# Move to the upper directory where this script is

cdir=$( dirname $0 )
cd $cdir/..

# Extract names and versions
TARNAME=$( readlink distrib/vnx-latest.tgz )  # vnx-latest.tgz is a symbolic link
                                              # with stat we get the name of the 
                                              # file pointed by the link
DIRNAME=$( echo "$TARNAME" | sed s/.tgz$// )
LONGVERNAME=$( echo "$DIRNAME" | sed s/vnx-// )
VERNAME=$( echo "$LONGVERNAME" | sed 's/-.*//g' )


echo "TARNAME=$TARNAME"
echo "DIRNAME=$DIRNAME"
echo "LONGVERNAME=$LONGVERNAME"
echo "VERNAME=$VERNAME"

# Create and clean destination folders
mkdir -p vnx-package/package/src/DEBIAN
mkdir -p vnx-package/package/src/tmp/VNX_tmp_install_files
rm -rf vnx-package/package/src/DEBIAN/*
rm -rf vnx-package/package/src/tmp/VNX_tmp_install_files/*

# Extract tar file to destination, removing first directory
tar -C vnx-package/package/src/tmp/VNX_tmp_install_files/ -xvf distrib/$TARNAME --strip 1

# Copy package files and update keys

cp vnx-package/base_files/PVARS vnx-package/package/
sed --in-place -e 's/PNAME\=\("pname"\)/PNAME\=\"nombrepaquete"/g' vnx-package/package/PVARS
sed --in-place -e 's/PVERS\=\("version"\)/PVERS\=\"'$VERNAME'"/g' vnx-package/package/PVARS

cp vnx-package/base_files/make vnx-package/base_files/make-p vnx-package/package/
cp vnx-package/base_files/control vnx-package/base_files/install_vnx vnx-package/base_files/postinst.in vnx-package/base_files/postrm.in vnx-package/base_files/prerm.in vnx-package/package/src/DEBIAN
